apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdr-ms-common-deployment
  namespace: cross
  labels:
    app: pdr-ms-common
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdr-ms-common
  template:
    metadata:
      labels:
        app: pdr-ms-common
    spec:
      containers:
      - name: pdr-ms-common
        image: registry.gitlab.com/bs2managers/pdr-ms-common:ic
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 9004
        env:
        - name: SPRING_CONFIG_URI
          valueFrom:
            secretKeyRef:
                name: configserver-security
                key: configserver.host
        - name: SPRING_CONFIG_BD_URL
          valueFrom:
            secretKeyRef:
                name: configserver-security
                key: bd.url
        - name: SPRING_CONFIG_BD_USERNAME
          valueFrom:
            secretKeyRef:
                name: configserver-security
                key: bd.username
        - name: SPRING_CONFIG_BD_PASSWORD
          valueFrom:
            secretKeyRef:
                name: configserver-security
                key: bd.password
      imagePullSecrets:
        - name: gitlab-auth-p