apiVersion: v1
kind: Service
metadata:
  name: pdr-ms-common
  namespace: cross
spec:
  ports:
  - name: http
    port: 9004
    protocol: TCP
    targetPort: 9004
  selector:
    app: pdr-ms-common
  type: NodePort
